[package]
name = "weibo-hot-topics"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_derive  = "1.0"
serde_json = "1.0"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
