name: cron-job

on:
  workflow_dispatch:
    inputs:
      my_parameter:
        description: 'A parameter to be used in the workflow'
        required: true

jobs:
  run_every_180_days_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run my script
        env:
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}  # 添加你的钉钉机器人 Webhook 地址到 GitHub 仓库的 Secrets 中
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"msgtype": "text", "text": {"content": " ${{ github.event.inputs.my_parameter }} github Actions 完成"}}' \
               ${DINGTALK_WEBHOOK}
