name: Main Workflow

on:
  workflow_run:
    workflows: ["timer_tips", "Update stackoverflow"]
    types:
      - completed

jobs:
  process_results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # 添加其他步骤和操作
      # ...

  send_notification:
    needs: process_results
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to DingTalk
        env:
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}  # 添加你的钉钉机器人 Webhook 地址到 GitHub 仓库的 Secrets 中
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"msgtype": "text", "text": {"content": "GitHub Actions 完成"}}' \
               ${DINGTALK_WEBHOOK}
        
      # - name: Step B
      # run: echo "任务流都已完成"
      # 添加其他步骤和操作
