name: Main Workflow

# 类似 dingding webhook 通过github dispatches 方式
# https://api.github.com/repos/logep/life-record/actions/workflows/5768305945/dispatches
# 'https://api.github.com/repos/logep/life-record/actions/workflows/cron-job.yml/dispatches'
# {
#   "ref": "main",
#   "inputs": {
#     "my_parameter": "example_value"
#   }
# }
# const url = 'https://api.github.com/repos/logep/life-record/actions/workflows/5768305945/dispatches';
# const token = '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'; // 替换为您的 Personal Access Token
# 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
# const headers = {
#   'Authorization': `token ${token}`,
#   'Content-Type': 'application/json',
# };

# const data = {
#   ref: 'main',
#   inputs: {
#     my_parameter: 'example_value',
#   },
# };

# fetch(url, {
#   method: 'POST',
#   headers: headers,
#   body: JSON.stringify(data),
# })
#   .then((response) => response.json())
#   .then((data) => console.log(data))
#   .catch((error) => console.error('Error:', error));

on:
  workflow_run:
    workflows: ["Update Hot Topics"]
    types:
      - completed

jobs:
  process_results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # 添加其他步骤和操作
      # ...
      - name: Step B
        run: echo "任务流都已完成"

  send_notification:
    needs: process_results
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to DingTalk
        env:
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}  # 添加你的钉钉机器人 Webhook 地址到 GitHub 仓库的 Secrets 中
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"msgtype": "text", "text": {"content": "github Actions 完成"}}' \
               ${DINGTALK_WEBHOOK}
#       - name: Send notification to WeChat
#         env:
#          SERVER_CHAN_SEND_KEY: ${{ secrets.SERVER_CHAN_SEND_KEY }}
#         run: |
#          curl -X POST -d "text=GitHub Actions Completed" https://sctapi.ftqq.com/$SERVER_CHAN_SEND_KEY.send

        

