name: Java Workflow

on:
   push:
     branches:
       - main
   schedule:
    - cron: "0 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Java Application
        run: java -jar target/auto_weibo.jar
        
      - name: Commit and push changes
        run: |
          git config --local user.email "pingbeer69@gmail.com"
          git config --local user.name "logep"
          git pull --rebase
          git add .
          git commit -m "Create go weibo"
          git push
