name: Generate Hot Topics by nodejs
on:
   push:
     branches:
       - main
   schedule:
    - cron: '54 0 * * *' # 每天 UTC 0:00 执行

jobs:
  generate-hot-topics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Generate Hot Topics Markdown
        run: node auto_nodejs.js

      - name: Commit and push changes
        run: |
          git config --local user.email "pingbeer69@gmail.com"
          git config --local user.name "logep"
          git pull --rebase
          git add .
          git commit -m "Create nodejs weibo"
          git push
