name: Update Hot Topics

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 7 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
   
      - name: Install dependencies
        run: pip install requests
   
      - name: Run script to add hot topics
        run: python auto_python.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "logep@github.com"
          git config --local user.name "logep"
          git add .
          git commit -m "Create new_file"
          git push
