name: Go Workflow

on:
#   push:
#     branches:
#       - main
  schedule:
    - cron: "0 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
          
      - name: Initialize Go module
        run: go mod init go/m
        
      - name: Build
        run: go build -o auto_weibo

      - name: Run
        run: ./auto_weibo
        
      - name: Commit and push changes
        run: |
          git config --local user.email "pingbeer69@gmail.com"
          git config --local user.name "logep"
          git pull --rebase
          git add .
          git commit -m "Create go weibo"
          git push
