name: Generate Hot Topics by nodejs
on:
   push:
     branches:
       - main
   schedule:
    - cron: '54 0 * * *' # 每天 UTC 0:00 执行

jobs:
  generate-hot-topics:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Generate Hot Topics Markdown
        run: node auto_nodejs.js
    
      - name: Generate random strings
        id: random_strings
        run: |
          # Generate 10 random strings and store them in an array
          random_strings=()
          for i in {1..10}; do
            random_strings+=($(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1))
          done
          # Export the array as an environment variable
          echo "RANDOM_STRINGS=${random_strings[*]}" >> $GITHUB_ENV

      - name: Set commit message
        id: commit
        run: |
          current_time=$(date +"%H:%M:%S")
          # Access the environment variable to get the random strings
          random_strings="${RANDOM_STRINGS}"
          echo "at $current_time with : $random_strings" >> commit_message.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "pingbeer69@gmail.com"
          git config --local user.name "logep"

          git add . -- :^node_modules/
          git commit -m "$(cat commit_message.txt)"
          git push -f
