name: weibo_scala

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8  # 11 或您所需的 Java 版本



    - name: Build and Test Scala
      run: |
        sbt clean && sbt compile && sbt run  # compile scala MyApp.scala 替换为您的构建和测试命令

    # 如果需要，您可以在此处添加其他步骤，例如部署到服务器或发布到存储库
    - name: Commit and push changes
      run: |
          git config --local user.email "pingbeer69@gmail.com"
          git config --local user.name "logep"
          git reset --hard HEAD
          git pull --rebase
          git add .
          git commit -m "Create weixin articles"
          git push -f
